### ISSUE TITLE
@Timed on @Stereotype

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-metrics#337]
CDI Stereotypes are very handy to not repeat the same set of annotations all over the place. I have one:

```java
@Retention(RUNTIME)
@Stereotype
@Timed
public @interface Boundary {
}
```

and use it:

```java
@Stateless
@Boundary
@Path("/orders")
public class OrderBoundary {
    @GET @Path("/{orderId}")
    public Order getOrder(@PathParam("orderId") long orderId) {
        ...
    }
}
```

I run this on a WildFly 20.0.1.Final and when I call this endpoint, I get an `java.lang.UnsupportedOperationException` at `io.smallrye.metrics//io.smallrye.metrics.interceptors.MetricResolver$DoesNotHaveMetric.metricName(MetricResolver.java:187)`. I don't get this exception, when I put the `@Timed` directly on the `OrderBoundary`.

**Comment by jmartisk** [comment]
This should be already fixed in 3.0 (not released yet) and 2.4.1 (already released), commit: https://github.com/smallrye/smallrye-metrics/commit/f8a8f002fde0db742bd90bc98234acce08c96ed5
WildFly 20.0.1.Final contains SR Metrics 2.4.0, so I guess we need to move this issue to the WildFly issue tracker to get an upgrade :)

**Comment by t1** [comment]
Thanks @jmartisk . Is 'we' you or me? ;-)

**Comment by jmartisk** [comment]
Let me take care of it: https://github.com/wildfly/wildfly/pull/13435
I'll close this issue then, if it turns out that it still doesn't work for you after the upgrade, feel free to open a new one :)
