### ISSUE TITLE
Make JmxWorker#findKeyForValueToBeReplaced more robust

### ISSUE THREAD

**Issue by jmesnil** [smallrye/smallrye-metrics#35]
During a code review, we identified several improvements for the JmxWorker class: https://github.com/smallrye/smallrye-metrics/blob/master/implementation/src/main/java/io/smallrye/metrics/JmxWorker.java#L156:

* iterate entrySet instead of keySet
* can it happen that there are more entries with value '*' ?
* shouldn't the for cycle end when the (first?) match is found ?

**Comment by rsvoboda** [comment]
@jmartisk any plans to look into this ?

**Comment by jmartisk** [comment]
That code has changed a lot since this issue was reported, so I'm looking into the history... The `findKeyForValueToBeReplaced` was reworked quite heavily with Metrics 2.0, because the placeholders are now used differently (an `ObjectName` reference in `base-metrics.properties` can have multiple placeholders `%s1`, `%s2` instead of just one), so the for-each loop was replaced by a Java stream pipeline that finds all `ObjectName` key properties containing placeholders in their values, and returns them as a map (that contains not just the keys, but both key and value). So while the original suggestions definitely made sense at that time, they don't apply anymore now.

What comes to my mind is that the name of that method `findKeyForValueToBeReplaced` doesn't quite fit anymore, because it now returns a map with potentially multiple entries. I guess `findObjectNameComponentsWithPlaceholders` would be a better name now.
