### ISSUE TITLE
moving scope into metrics metadata?

### ISSUE THREAD

**Issue by jmesnil** [smallrye/smallrye-metrics#50]
What is the rationale between having `base:`, `vendor:` and `application:` prefix in the Prometheus output format?
 
I have a system with existing "vendor" metrics exposed to Prometheus directly. I would like to use smallrye-metrics but preserve my metric names.
Ideally, I'd prefer to have the microprofile-metrics scope being a label attached to the metrics, so that instead of:

```
vendor:my_existing_metric{foo="bar"}
```

I would have something like:

```
my_existing_metric{foo="bar", microprofile-scope="vendor"}
```

**Comment by kenfinnigan** [comment]
I think it's to separate out the different kind of metrics that can be retrieved.

Can't recall if hitting each of those endpoints directly still has the prefix or its removed

**Comment by jmartisk** [comment]
Prepending the scope is required by the Metrics specification (with 2.0 it's now `vendor_` instead of `vendor:`). We could support moving it into a tag as opt-in through a config property or something.

But I see a potential issue if two metrics in different scopes have the same names, they will suddenly be under the same name in the output (and appear as two variants of the same metric) but can potentially be of different types (and have different description etc.), so I'm not sure what we would do with the `TYPE` and `HELP` lines for these metrics (there is one TYPE and one HELP line per metric name, regardless of the number of actual metrics with that name).
