### ISSUE TITLE
The type casts in the exporters are too restrictive

### ISSUE THREAD

**Issue by pe-st** [smallrye/smallrye-metrics#51]
For the types METERED, TIMER and HISTOGRAM the type casts in

- `io.smallrye.metrics.exporters.JsonExporter#writeMetricsForMap` and
- `io.smallrye.metrics.exporters.PrometheusExporter#exposeEntries`

are too strict, they allow only the XxxImpl types, but an application might want to register another metrics type implementing the given interfaces.

**Comment by jmartisk** [comment]
Well, how do you envision that an application would do that? To use a different implementation class, one would probably have to customize SmallRye Metrics by adding the new class and changing the metric registration logic so that it will register an instance of the new class. AFAIK there's no easy way to plug in a new implementation class without changing the SmallRye code, so this doesn't look like a very feasible use case at the moment, but yeah, in future it could potentially be useful.

**Comment by pe-st** [comment]
A different implementation can't currently used via the `@Metered` annotation, I agree.

But you can still register it to the application MetricsRegistry, call `mark()` (for a `Meter` metric) on it manually and the have it exported together with all other application metrics.

The MicroProfile metrics spec explains how to [get the MetricsRegistry](https://github.com/eclipse/microprofile-metrics/blob/master/spec/src/main/asciidoc/app-programming-model.adoc#application-metric-registry):

    @Inject
    @RegistryType(type=MetricRegistry.Type.APPLICATION)
    MetricRegistry metricRegistry;

Then you can register any metric class implementing the interface `Metric` (example from the [spec](https://github.com/eclipse/microprofile-metrics/blob/master/spec/src/main/asciidoc/app-programming-model.adoc#metadata)):

    Meter me = new MyMeterImpl();
    metricRegistry.register(m, me);

As the exporters only use the standard interfaces to extract the data, they don't need to know the implementation of a metric at all.

In my [pull request](https://github.com/smallrye/smallrye-metrics/pull/52) I basically do that in the unit test `exportOneMetric_metered()`: I register the class `SomeMeter` and show that it (with my fix) can be used with the exporter and has the same output as the Smallrye class `MeterImpl`.

**Comment by pe-st** [comment]
Should be fixed in the next release with the merge of #52
