### ISSUE TITLE
Add priviledged block, since eclipse.Metadata does System.getEnv

### ISSUE THREAD

**Issue by baranowb** [smallrye/smallrye-metrics#55]
https://github.com/eclipse/microprofile-metrics/blob/branch-1.1/api/src/main/java/org/eclipse/microprofile/metrics/Metadata.java#L142

**Comment by baranowb** [comment]
Ref: https://issues.jboss.org/browse/WFLY-11499

**Comment by jmartisk** [comment]
This is fixed in Metrics 2.0-1.0.0 because obtaining system properties is now correctly delegated to MP Config. SmallRye Config had a similar issue where obtaining system properties was not in a privileged block, but this is fixed in SR Config 1.3-1.0.0, so the runtime framework has has to make sure to use this. I think we can close this as there is nothing more we can do on SmallRye Metrics side.
