### ISSUE TITLE
Apply tag filter to the (Micrometer)  global composite meter registry

### ISSUE THREAD

**Issue by Channyboy** [smallrye/smallrye-metrics#584]
Currently, the MP metrics global tags (`mp.metrics.tags`) are set with a filter to the Prometheus Meter registry or Simple Meter Registry in the `SharedMetricRegistries.resolveMPConfigGlobalTagsByServer()`. This should be updated to affect the global composite meter registry so that other meter registries (i.e. elastic, dynatrace, graphite, etc) would have the `mp.metrics.tags`.

**Comment by donbourne** [comment]
A key justification for why we need this:

Any metrics the MP api adds to the global meter registry needs to have the same tags in every member of the composite meter registry, otherwise you end up with the problem where calling the composite to get a value for a particular metric could return different values depending on which member of the composite responds.

That said, it may be surprising/undesirable, for app developers that are adding their own metrics using the micrometer api directly, to find that we've added MP-specific tags to their metrics.  So perhaps we should only add MP-specific tags to metrics registered by MP.
