### ISSUE TITLE
MetricRegistry.counter("name") fails if a reusable counter "name" already exists

### ISSUE THREAD

**Issue by Ladicek** [smallrye/smallrye-metrics#85]
I'm trying to use `myMetricRegistry.counter("name.of.the.counter")` to get hold of an already existing counter. However, I'm getting an exception: `java.lang.IllegalArgumentException: Previously registered metric name.of.the.counter was flagged as reusable, while current request is not.` I'm looking at the javadoc of `MetricRegistry.counter(String)` and my understanding is that if a counter already exists, it should just return it, no matter how it was created.

Lookign at the implementation, it seems to me that the checks performed in `MetricsRegistryImpl.get(Metadata, MetricType)` in case of an already existing metric are overly restrictive. Even the `MetricRegistry.counter(Metadata)` method (and it's the same for other kinds of metrics) is documented to "Return the Counter registered under the Metadata's _name_" (note that it only mentions name, no other characteristics of the metric!).

**Comment by Ladicek** [comment]
Simple workaround is to use `myMetricRegistry.getCounters().get("name.of.the.counter")`, but I like shorter code :-)

**Comment by jmartisk** [comment]
Thanks for the report :) this logic in `MetricRegistryImpl` in 1.x is indeed a bit flawed and confusing (and the Metrics specification doesn't bring much light into it either). The problem is that `registry.counter(name)` basically translates itself into `registry.counter(metadata)` by building a Metadata object, but obviously it has no way to say whether it should set `reusable=true` in that object (and currently it doesn't). 

This issue is basically the same as https://github.com/smallrye/smallrye-metrics/issues/43 where we decided that for backward compatibility, we will keep it as it is in 1.x, 2.0 will fix it.

**Comment by Ladicek** [comment]
I'm gonna claim the Metrics specification is very clear about these methods :-) Citing from http://static.javadoc.io/org.eclipse.microprofile.metrics/microprofile-metrics-api/1.1.1/org/eclipse/microprofile/metrics/MetricRegistry.html:

`counter(Metadata)`: "Return the Counter registered under the Metadata's name ..."
`counter(String)`: "Return the Counter registered under this name ..."
same for `histogram()`, `meter()` and `timer()`

All the `reusable` concerns are very much valid in case the call would result in registering a new metric. But if the metric already exists, there's no such concern, and the javadoc for these methods clearly states that the existing metric is looked up _by the name_ and nothing else.

**Comment by Ladicek** [comment]
I've see #43 yesterday and thought it's something else, but I'm reading it again and it's true it's pretty much the same as this issue. Gonna close this one.
