### ISSUE TITLE
Master build is failing

### ISSUE THREAD

**Issue by sberyozkin** [smallrye/smallrye-metrics#99]
There are 10 test failures on the master branch at the moment

**Comment by sberyozkin** [comment]
@jmartisk, @jmesnil  FYI, https://semaphoreci.com/smallrye/smallrye-metrics/branches/pull-request-98/builds/1

Note this was failing before and after my PR for me locally.

**Comment by kenfinnigan** [comment]
I suspect it's because the 2.x work is still in progress

**Comment by jmartisk** [comment]
Yes this is because we are working on 2.0. Specification and implementation are being worked on in parallel, and we don't release a snapshot of the specification after each commit so the spec and impl sometimes don't match. That's why we introduced the "Build with current MP SNAPSHOT" job in Semaphore, which always builds the current master of the spec, and then builds SR Metrics against that. So there are now two jobs in Semaphore, if at least one of them passes, then probably everything's fine.

**Comment by sberyozkin** [comment]
Thanks for the explanation. I'll close this issue
